Allow encryption of Kubernetes resources
gravitational/planet pull request #865
Opened 2021-09-29 18:22 UTC by bernardjkim

## Description
These changes allow Kubernetes resources to be encrypted at rest. Planet now takes flags for:
- `--encryption-provider`
- `--aws-account-id`
- `--aws-key-id`
- `--aws-key-region`

If encryption is enabled, the `aws-encryption-provider` will run as a systemd service and the `kube-apiserver` will be configured by `encryption-configuration.yaml` to connect to the `aws-encryption-provider`.

Just some clean up. It looks like `master-docker.mk` is unused and is the same as `planet.mk`

2021-10-01 23:37 UTC, wadells commented
> Just some clean up. It looks like master-docker.mk is unused and is the same as planet.mk

Would you split these out into a separate PR please?  I'm all for clean up, but it gives a much cleaner history if orthogonal changes are independent.

2021-10-04 21:03 UTC, wadells requested changes
My big concern is the encryption provider build/version doesn't seem to be pinned.

Other concerns are minor.

2021-10-05 01:21 UTC, bernardjkim commented on Dockerfile
> +RUN chmod a+rwx /etc/kmsplugin
The `kube-apiserver` is running as `user=planet` and `group=planet`. So we needed a place to create the `encryption-provider.sock` socket file with planet ownership to allow the apiserver to connect to the socket. I'm not sure if this was the best way to handle this. If there is a better way, let me know.
Updated in 4600a60

2021-10-05 01:36 UTC, bernardjkim commented on build.assets/makefiles/encryption/aws-encryption-provider.service
> +	--key=arn:aws:kms:${AWS_KEY_REGION}:${AWS_ACCOUNT_ID}:key/${AWS_KEY_ID} \
The `kube-apiserver` is running as `user=planet` and `group=planet`. So we needed a directory to create the `encryption-provider.sock` socket file with planet ownership to allow the apiserver to connect to the socket. I'm not sure if this was the best way to handle this. If there is a better way, let me know.
Updated in 4600a60

2021-10-05 01:36 UTC, bernardjkim commented on build.assets/makefiles/encryption/encryption.mk
> +	cd /tmp/kubernetes-sigs && git clone https://github.com/kubernetes-sigs/aws-encryption-provider --depth 1
The repo doesn't provide any tags. In this case do we want to just fork and create our own tag?

2021-10-05 15:57 UTC, wadells commented on build.assets/makefiles/encryption/aws-encryption-provider.service
> +	--key=arn:aws:kms:${AWS_KEY_REGION}:${AWS_ACCOUNT_ID}:key/${AWS_KEY_ID} \
Ok. I'm happy with current strategy.  It sounds like using only an ARN would probably introduce too much magic into the planet/gravity code, even if it does keep configuration simpler.

2021-10-05 15:58 UTC, wadells commented on build.assets/makefiles/encryption/encryption.mk
> +	cd /tmp/kubernetes-sigs && git clone https://github.com/kubernetes-sigs/aws-encryption-provider --depth 1
No fork needed, but in lieu of tags, please check out a specific commit sha.

2021-10-05 16:02 UTC, wadells commented on Dockerfile
> +RUN chmod a+rwx /etc/kmsplugin
This seems fine to me -- the comment was helpful.

2021-10-05 19:04 UTC, bernardjkim commented on build.assets/makefiles/encryption/encryption.mk
> +	cd /tmp/kubernetes-sigs && git clone https://github.com/kubernetes-sigs/aws-encryption-provider --depth 1
Updated in 6df5190

2021-10-07 17:41 UTC, wadells approved these changes

2021-10-08 23:42 UTC, merged